apiVersion: v1
kind: persistentVolume
metadata:
  name: database-persistent-volume
spec:
  storageClassName: manual
  capacity: 
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"